# Generated by Django 5.0 on 2025-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_auth_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
