# Generated by Django 5.0 on 2025-03-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
