# Generated by Django 5.0 on 2025-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/api/images/defaults.png', null=True, upload_to='avatars/'),
        ),
    ]
