# Generated by Django 5.0 on 2025-04-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default1.png', null=True, upload_to='avatars/'),
        ),
    ]
