# Generated by Django 5.0 on 2025-03-04 16:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_update_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score_p1', models.IntegerField(default=0)),
                ('score_p2', models.IntegerField(default=0)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_match_history', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_match_history', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
            },
        ),
    ]
