# Generated by Django 5.0 on 2025-03-31 10:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=api.models.User.get_default_avatar, null=True, upload_to='avatars/'),
        ),
    ]
