# Generated by Django 5.0 on 2025-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_temp_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('default1', 'Avatar 1'), ('default2', 'Avatar 2')], default='default1', max_length=50),
        ),
    ]
