# Generated by Django 5.0 on 2025-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('default1', 'Avatar 1'), ('default2', 'Avatar 2')], default='default2', max_length=50),
        ),
    ]
