# Generated by Django 5.0 on 2025-04-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
    ]
