server {

	listen       80;
	listen  [::]:80;
	server_name  localhost;

	return 301  https://$host:__HTTPS_PORT__$request_uri;
}


server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name localhost;


	#SSL configuration
	ssl_certificate /etc/nginx/ssl/fullchain.pem;
	ssl_certificate_key /etc/nginx/ssl/privkey.pem;

# Security Headers
        add_header Strict-Transport-Security "max-age=63072000" always; # Enforce us of https
        add_header X-Frame-Options "SAMEORIGIN" always; # Prevent clickjacking by preventing page to be embedded in iframe
        add_header X-XSS-Protection "1; mode=block" always; # Enable xss protection by preventing browser to display page when xss attack is detected
        add_header X-Content-Type-Options "nosniff" always; # Make browser stick to declared mimetype file and to don't sniff file to guess type
        add_header Referrer-Policy "no-referrer-when-downgrade" always;# Control what information are sent as referer header. option between quote simply prevent referer to be sent when switching to a non-https site
        #add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval'" always; # Prevent resources to be loaded outside of our domain
        add_header Permissions-Policy "camera=(), microphone=(), geolocation=()"; #Prevent site access to camera, microphone and geoloc'


	#access_log  /var/log/nginx/host.access.log  main;

	# Optional: MIME types and headers
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	index  index.html;

	location ~* ^/(?!wss/).* {
		root   /usr/share/nginx/html;
		try_files $uri $uri/ /index.html;
	}



	location /wss/ {
#		proxy_pass http://backend:__SOCKET_PORT__;
		proxy_pass http://backend:8000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_set_header origin $http_origin;
	}


	# redirect server error pages to the static page /50x.html
	#
	error_page  404              /404.html;
	error_page   500 502 503 504  /50x.html;
	location = /50x.html {
		root   /usr/share/nginx/html;
	}

	# proxy the PHP scripts to Apache listening on 127.0.0.1:80
	#
	#location ~ \.php$ {
		#    proxy_pass   http://127.0.0.1;
		#}

	# pass the api call to django backend at backend:8000

#location /api/ {
#	proxy_pass   http://backend:8000;
#	proxy_set_header Host $host; #Pass original hostname
#		proxy_set_header X-Real-IP $remote_addr; #Pass actual ip adress
#		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#}
	# Security headers
	#	add_header Strict-Transport-Security "max-age=63072000" always;
	#	add_header X-Content-Type-Options nosniff;
	#	add_header X-Frame-Options "SAMEORIGIN";
	#	add_header X-XSS-Protection "1; mode=block"; #Block Xss attack

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
		#    deny  all;
		#}
}
