# Dockerfile.dev
FROM node:23-alpine

WORKDIR /app

# We don't need COPY commands for dependencies or source code
# as they will be mounted through volumes

COPY --chmod=700 setup_dev.sh /root/setup.sh

# Expose Vite dev server port
EXPOSE 5173

# Start development server
#CMD ["/root/entrypoint.sh"]
#CMD ["npm", "run", "dev"]
