FROM nginx:alpine

ARG HTTPS_PORT
ARG SOCKET_PORT

COPY default.conf /etc/nginx/conf.d/default.conf

COPY ./src/ /usr/share/nginx/html

RUN echo "$HTTPS_PORT" > /tmp/ports

RUN sed -i "s/__HTTPS_PORT__/$HTTPS_PORT/g" /etc/nginx/conf.d/default.conf 
RUN sed -i "s/__HTTPS_PORT__/$HTTPS_PORT/g"  /usr/share/nginx/html/js/api/config/apiConfig.js
