services:

# Frontend production container: Enforced Nginx server with healthcheck
# -----------------------------------------------------------------------------------------------------------
  frontend-prod:
    container_name: frontend
    pull_policy: never
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
      args:
        - HTTPS_PORT=${HTTPS_PORT}     # Needed to adapt nginx redirection
    image: frontend:local
    ports:
      - "${FRONT_PORT}:80"          # Port exposing HTTP scheme
      - "${HTTPS_PORT}:443"         # Port exposing HTTPS scheme
    volumes:
      - ./frontend/src:/usr/share/nginx/html:rw,z  # Bind mount for development
        #      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw,z  # Nginx configuration
      - ./nginx/ssl:/etc/nginx/ssl:rw,z  # ssl certificate
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - prod   # Profiles are here to separate container needed in prod and in dev environment


# Frontend dev container: run with Vite and Node for Hot reloading option, Easy installation and Dev Tool
# --------------------------------------------------------------------------------------------------------------------
  frontend-dev:
    container_name: frontend
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: frontend:local
    ports:
      - "${FRONT_PORT}:3000"
    volumes:
      - ./frontend/src:/app/src:rw,z  # Bind mount for development
        #      - ./frontend/public:/app/public:rw,z  # Public assets
      - ./frontend/dev/node_modules:/app/node_modules:rw,z  # Dev dependencies
      - ./frontend/dev/package.json:/app/package.json:rw,z  # Package management
      - ./frontend/dev/package-lock.json:/app/package-lock.json:rw,z  # Package management
      - ./frontend/cfg/vite.config.js:/app/vite.config.js:rw,z
        #    - ./frontend/dev/vite.config.js:/app/vite.config.js:rw,z  # Vite config
        #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw,z  # Nginx configuration
        #    - ./nginx/ssl:/etc/nginx/ssl:rw,z  # ssl certificate
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:${BACK_PORT}
    working_dir: /app
    command: npm run dev
    profiles:
      - dev   # Profiles are here to separate container needed in prod and in dev environment


# Backend service: Run with django. Provide API for user management and data retrieval. Also Socket for pong game
# --------------------------------------------------------------------------------------------------------------------
  backend:
    container_name: backend
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: backend:local
    command: /root/setup.sh
    ports:
      - "${BACK_PORT}:8000"
    environment:
        #     - DEBUG=1
        #     - DJANGO_SETTINGS_MODULE=project.settings.development
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
        #- JWT_SECRET_KEY=your-secret-key-here
    volumes:
      - ./backend/src:/app:rw,z  # Mount backend code
    profiles:
      - prod
      - dev

# Database service: Provide user management databases for authentication and user metrics
# --------------------------------------------------------------------------------------------------------------------
  db:
    image: postgres:15-alpine
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - prod
      - dev

volumes:
  postgres_data:
