
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: frontend:local
    ports:
      - "${FRONT_PORT}:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html:rw,z  # Bind mount for development
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw,z  # Nginx configuration
    
# Backend service
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: backend:local
    command: /root/setup.sh
    ports:
      - "${BACK_PORT}:8000"
    environment:
        #     - DEBUG=1
        #     - DJANGO_SETTINGS_MODULE=project.settings.development
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
        #- JWT_SECRET_KEY=your-secret-key-here
    volumes:
      - ./backend/src:/app:rw,z  # Mount backend code

  db:
    image: postgres:15-alpine
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
