
services:

  frontend-prod:
    container_name: frontend
    pull_policy: never
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
      args:
        - HTTPS_PORT=${HTTPS_PORT}
    image: frontend:local
    ports:
      - "${FRONT_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./frontend/src:/usr/share/nginx/html:rw,z  # Bind mount for development
        #      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw,z  # Nginx configuration
      - ./nginx/ssl:/etc/nginx/ssl:rw,z  # ssl certificate
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - prod   # Profiles are here to separate container needed in prod and in dev environment

  frontend-dev:
    container_name: frontend
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - HTTPS_PORT=${HTTPS_PORT}
    image: frontend:local
    ports:
      - "${FRONT_PORT}:5173"
    volumes:
      - ./frontend/src:/app:rw,z  # Bind mount for development
        #      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw,z  # Nginx configuration
      - ./nginx/ssl:/etc/nginx/ssl:rw,z  # ssl certificate
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - dev   # Profiles are here to separate container needed in prod and in dev environment
    
# Backend service
  backend:
    container_name: backend
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: backend:local
    command: /root/setup.sh
    ports:
      - "${BACK_PORT}:8000"
    environment:
        #     - DEBUG=1
        #     - DJANGO_SETTINGS_MODULE=project.settings.development
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
        #- JWT_SECRET_KEY=your-secret-key-here
    volumes:
      - ./backend/src:/app:rw,z  # Mount backend code
    profiles:
      - prod
      - dev

  db:
    image: postgres:15-alpine
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - prod
      - dev

volumes:
  postgres_data:
