FROM  python:3-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \ 
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt /root
COPY setup.sh /root

RUN chmod +x /root/setup.sh

ENV PATH "/app/venv/bin:$PATH"

# The application code is mounted as a volume in development
