# ELK stack compose file

services:
  # setup:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
  #     #   volumes:
  #     #     certs: /usr/share/elasticsearch/config/certs
  #   command: ./Elasticsearch/entrypoint.sh
  #   environment:
  #    - xpack.security.enabled=false
  #    - xpack.security.http.ssl.enabled=false
  #    - xpack.security.transport.ssl.enabled=false
  #   profiles:
  #     - prod
  #   networks:
  #     - elk_network

  es01:
     #  depends_on:
     #    setup:
     #      condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es01
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      #    - certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
        #    - xpack.security.http.ssl.key=certs/es01/es01.key
        #    - xpack.security.http.ssl.certificate=certs/es01/es01.crt
        #    - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
        #    - xpack.security.transport.ssl.key=certs/es01/es01.key
        #    - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
        #    - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
        #    - xpack.security.transport.ssl.verification_mode=certificate
    mem_limit: ${ES_MEM_LIMIT}
      #ulimits:
      #  memlock:
      #    soft: -1
      #    hard: -1
    profiles:
      - prod
    networks:
      - elk-network
    healthcheck:
      #test:
      #  [
      #    "CMD-SHELL",
      #    "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
      #  ]
      test:
        [
          "CMD-SHELL",
          "curl -s https://localhost:9200 | grep -q 'ElasticSearch is down'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


volumes:
  #certs:
  #  driver: local
 esdata01:
   driver: local
 kibanadata:
   driver: local
 logstashdata01:
   driver: local

networks:
  elk-network:
    driver: bridge
    name: elk
