input {
	gelf {
		port => 12201
		type => "docker"
	}
}


filter {
}


output {
	elasticsearch {
		hosts=> "${ELASTIC_HOSTS}"
		index => "docker-logs-%{+YYYY.MM.dd}"
#		user=> "${ELASTIC_USER}"
#		password=> "${ELASTIC_PASSWORD}"
#   cacert=> "certs/ca/ca.crt"
	}
}
